---
#-----------------------------------------
# CloudBuild Pipeline for Prod CloudRun
#-----------------------------------------
steps:
  - name: docker/compose:latest
    id: BUILD
    entrypoint: ['docker-compose']
    args: ['build']
