name: CI and CD Pipeline to Cloud Run
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set environment variables
        run: echo "Setting environment variables"
        env:
          IMAGE_VERSION: ${{ github.ref_name }}
      # - name: Set up Google Cloud SDK
      #   uses: google-github-actions/auth@v2
      #   with:
      #     workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      #     service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Auth Container Registry
        run: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Setup Secret for Pulling Image
        run: gcloud secrets create cloud-run-secret --replication-policy automatic
      - name: Build and push Docker image Backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.back
          push: true
          tags: ghcr.io/$GITHUB_REPOSITORY/cloud-run-back:$IMAGE_VERSION
      - name: Build and push Docker image Frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.front
          push: true
          tags: ghcr.io/$GITHUB_REPOSITORY/cloud-run-front:$IMAGE_VERSION
      # - name: Deploy to Cloud Run Backend
      #   uses: google-github-actions/deploy-cloudrun@v2
      #   with:
      #     service: cloud-run-back
      #     image: ghcr.io/$GITHUB_REPOSITORY/cloud-run-back:$IMAGE_VERSION
      #     region: us-central1
      # - name: Deploy to Cloud Run Frontend
      #   uses: google-github-actions/deploy-cloudrun@v2
      #   with:
      #     service: cloud-run-front
      #     image: ghcr.io/$GITHUB_REPOSITORY/cloud-run-front:$IMAGE_VERSION
      #     region: us-central1
